apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  labels:
    app: web
spec:
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web-application
          image: balachandiran61/argocd-web-app:2.0
          containerPort: 5000
  replicas: 5
  selector:
    matchLabels:
      app: web
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause: {duration: 120}
      - setWeight: 40
      - pause: {duration: 10}
      - setWeight: 60
      - pause: {duration: 10}
      - setWeight: 80
      - pause: {duration: 10}

      
